"""
grid.py – Grid and Cell Modelling
===================================
Defines the 2-D simulation domain.

Each grid cell represents a geographic tile and stores:
  - population_density : synthetic persons-per-cell (spatially smooth)
  - resistance         : structural resistance factor in [0, 1]

Population density is generated by:
  1. Drawing a random matrix
  2. Applying a Gaussian blur (scipy.ndimage) to produce spatial correlation
  3. Rescaling to [0, MAX_POPULATION]

This produces realistic-looking urban/rural gradients without real GIS data.

Resistance is generated similarly with a smoother kernel, representing the
aggregate construction quality of all buildings in the cell.

EDUCATIONAL NOTE:
  Real seismic vulnerability depends on building typology (masonry, RC frame,
  timber), age, code compliance, soil type (site amplification), and more.
  Our single 'resistance' field is a gross simplification intended to illustrate
  the concept of differential damage across a heterogeneous landscape.
"""

import numpy as np
from scipy.ndimage import gaussian_filter
import config


def _smooth_random(shape: tuple, sigma: float, seed: int | None = None,
                   rng: np.random.Generator | None = None) -> np.ndarray:
    """
    Generate a spatially-smooth random field in [0, 1].

    Parameters
    ----------
    shape  : (rows, cols) output shape
    sigma  : Gaussian blur standard deviation (controls spatial correlation length)
    seed   : Optional RNG seed (used only when rng is None)
    rng    : Pre-constructed numpy Generator (takes priority over seed)

    Returns
    -------
    Smoothed, normalised ndarray with values in [0, 1].
    """
    if rng is None:
        rng = np.random.default_rng(seed)
    raw = rng.random(shape)
    blurred = gaussian_filter(raw, sigma=sigma)
    # Normalise to [0, 1]
    blurred -= blurred.min()
    blurred /= blurred.max() if blurred.max() > 0 else 1.0
    return blurred


class SeismicGrid:
    """
    Container for the 2-D simulation domain.

    Attributes
    ----------
    size              : int  – side length of the square grid
    population_density: ndarray (size × size) – synthetic population per cell
    resistance        : ndarray (size × size) – structural resistance in [0, 1]
    """

    def __init__(self, size: int = config.GRID_SIZE, seed: int | None = config.RANDOM_SEED):
        self.size = size
        rng = np.random.default_rng(seed)

        # --- Population density -------------------------------------------
        # Larger sigma → broader urban clusters
        pop_field = _smooth_random((size, size), sigma=size * 0.12, rng=rng)
        self.population_density: np.ndarray = pop_field * config.MAX_POPULATION

        # --- Structural resistance ----------------------------------------
        # Smoother field (sigma larger relative to pop) → more gradual
        # transitions between high/low-quality construction zones.
        res_raw = _smooth_random((size, size), sigma=size * 0.18, rng=rng)
        # Rescale to [RESISTANCE_MIN, RESISTANCE_MAX]
        span = config.RESISTANCE_MAX - config.RESISTANCE_MIN
        self.resistance: np.ndarray = config.RESISTANCE_MIN + res_raw * span

        # Cache for coordinate meshgrid (filled lazily)
        self._row_coords: np.ndarray | None = None
        self._col_coords: np.ndarray | None = None

    # ------------------------------------------------------------------
    # Coordinate helpers
    # ------------------------------------------------------------------
    @property
    def row_coords(self) -> np.ndarray:
        """Row indices matrix (size × size)."""
        if self._row_coords is None:
            self._row_coords, self._col_coords = np.mgrid[
                0:self.size, 0:self.size
            ]
        return self._row_coords

    @property
    def col_coords(self) -> np.ndarray:
        """Column indices matrix (size × size)."""
        if self._col_coords is None:
            _ = self.row_coords  # triggers both
        return self._col_coords

    def distance_from(self, epicenter: tuple[int, int]) -> np.ndarray:
        """
        Vectorised Euclidean distance from *epicenter* to every grid cell.

        Parameters
        ----------
        epicenter : (row, col) epicenter coordinates in grid units

        Returns
        -------
        ndarray (size × size) of distances in grid-cell units.

        NOTE: We use straight-line (isotropic) distance without any correction
        for Earth's curvature or topographic path effects.  For a 100×100 grid
        representing e.g. 100 km², this is a minor concern.
        """
        er, ec = epicenter
        dr = self.row_coords - er
        dc = self.col_coords - ec
        return np.sqrt(dr**2 + dc**2)

    def summary(self) -> str:
        """Return a short human-readable description of the grid."""
        return (
            f"Grid size          : {self.size} × {self.size} cells\n"
            f"Total population   : {self.population_density.sum():,.0f} persons\n"
            f"Mean resistance    : {self.resistance.mean():.3f}\n"
            f"Resistance range   : [{self.resistance.min():.3f}, {self.resistance.max():.3f}]"
        )
